### PR TITLE
PDS3 tables and other changes; update to PdsLogger required also

### PR DESCRIPTION
**Pull request by markshowalter**
# Additions

- `pdstemplate/pds3table.py` contains support tools for PDS3 templates or labels that describe ASCII tables.
- `pdstemplate/asciitable.py` is used by the above; it contains general support tools for ASCII table that would also be suitable for use by a future pds4table.py module.

You can work with the new classes Pds3Table and AsciiTable directly, but it'll be much more common to use the pre-processor and/or the predefined template functions:

- `ANALYZE_TABLE` will construct an AsciiTable object and save it as the global default.
- `TABLE_VALUE` provides access to the information obtained by the most recent call to ANALYZE_TABLE.
- `ANALYZE_PDS3_LABEL` constructs a Pds3Table object and saves it as the global default.
- `VALIDATE_PDS3_TABLE` performs validation of the current label against the current table generates a warning message for each error found. (Alternatively, use `ANALYZE_PDS3_LABEL` with `validate=True`.
- `LABEL_VALUE` provides access to correct information to appear in the PDS3 label when it is generated.
- `OLD_LABEL_VALUE` provides access to the possibly incorrect information in the current label or template.

I would imagine that a new template would simply start with
```
$ONCE(ANALYZE_TABLE (...))
$ONCE(ANAYZE_PDS3_LABEL(...))
```
and then use `LABEL_VALUE` extensively to place desired values into the template.

Alternatively, one can use the `pds3_table_preprocessor` on an existing label to transform it into a template in which all required PDS3 table parameters are replaced by calls to `LABEL_VALUE`. Then, `template.write()` with `mode="save"` or `mode="repair"` will write a new label containing any corrections. Alternatively, the `mode="validate"` option will report any errors but not save the file.

Although I have not created it, it would be straightforward to create a stand-alone PDS3 label validator that checks a given label/table pair and reports any errors. Similarly, a standalone label repair tool could take a label/table pair, validate the label, and write a new label if there are any changes.

All validation errors are reported as warning messages sent to the logger.

# Changes

- The user can include one or more pre-processor functions when constructing a PdsTemplate. There's also a placeholder for the planned include file preprocessor.
- Previously, `logger` was an input to the PdsTemplate constructor and also to `write` and `generate`. This was silly; if the user wants to control what they see, it's really a matter of what handlers they attach to the logger. So now, a single logger is global. It can be accessed through functions `set_logger`, `get_logger`, `set_log_level`, and `set_log_format`. There's an option to specify one or more unique handlers for each call to `generate` or `write`, so if a user wants a separate log file for each label generated, they can create them.
- Previously, there was line terminator control in generate() and write(). This was silly because when would you need to write the same template using different terminators? Now it's exclusively an input the the PdsTemplate constructor.
- There's some new tests for line terminator consistency and a utility `_check_terminators` that raises exceptions if something is amiss.
- All reads and writes have been converted to binary to ensure that line terminators are preserved.
- Some of the previous content of `__init__.py` has been moved to `_utils.py` and`_pdsblock.py.`
- Previously, the default logger was a `NullLogger`, which had the nasty habit of failing silently--probably not what we really want. Now it's a basic `PdsLogger`. BTW a new feature of `PdsLogger` is that if the user has not assigned it any handlers, it will write messages to the terminal.
- Global variables are inevitable in this system, because the pre-defined functions execute inside the template without any context. However, the manner in which the globals are defined is now a lot cleaner. Each time a `PdsTemplate`, `AsciiTable`, or `Pds3Table` object is created or accessed, it automatically defines itself as the global default of that class. The pre-defined functions can then just access whatever objects they need. The current label path and dictionary in use by `generate()` are also globally available when generation is in progress.
- As alluded to above, the `mode` option on `template.write` lets the user specify whether to `save` the file, `repair` it (save it only if something has changed) or just `validate` it. There's also an option to save a backup of a pre-existing file.
- VERSION_ID() now returns only two digits, and those digits are "0.0" if the version is unspecified.
- LOG() sends a message to the logger.
- I fixed up the way that the dictionaries are handled inside `_LabelState`. This cleaned up some code but has no other significance.

# Known Problems

- Test coverage is no longer 100% but it's decent.
- I've attempted to make sphinx-friendly docstrings but have not tested any of them.

### CODE REVIEW

**Review by jnspitale — COMMENTED** [review]
Not sure what's going on with the automatic tests failing.  Also, it's not clear how the unit tests are intended to be run as none of them call unittest.main(), but I added that temporarily and ran all of the tests successfully.

**Comment by pds-admin** [comment]
> Not sure what's going on with the automatic tests failing. Also, it's not clear how the unit tests are intended to be run as none of them call unittest.main(), but I added that temporarily and ran all of the tests successfully.

There are three ways to run the unit tests:

```
python -m unittest
```

or

```
pytest
```

or

```
python -m pytest
```

Also I'm fixing the tests. They require Python 3.10 or later and also there were issues with Windows.

**Comment by markshowalter** [comment]
More updates added to address some of Joe's issues and also to implement `$INCLUDE` (because, once I saw clearly how to do it, I couldn't look away).

- Predefined function `GETENV` is implemented.
- I refined the regular expressions for TABLEs and COLUMNs in `pds3table.py`; they should be more robust.
- The user can manage a list of directories to search for include files in two ways. There's the `PDSTEMPLATE_INCLUDES` environment variable, but the use can also identify directories using the `includes` input to the PdsTemplate constructor.
- BTW, if you ever want to know exactly what the template looks like _after_ pre-processing, look at the `content` attribute. I think that makes it easier to understand how pre-processors work.

# Unit Tests

Coverage is in the mid-90s and most un-tested code is related to edge cases. We can do better, sure, but I think this is adequate for now.

I added a bunch of new test files, including `sky_summary_template.txt`, which is my take on what a PDS3 ASCII table template should look like. It contains the minimum set of parameters required to define each column. Everything else gets added by the preprocessor. In general, explicit calls to `$LABEL_VALUE` are rarely needed, because the pre-processor adds them silently (or with a warning if you prefer). I'm hoping Joe can use this as a starting point for his other templates. Also, if he wants to add the explicit FORMAT values to the template (rather than having formats inferred from an existing table), he could potentially turn a template into a driver for his supplemental index generator.

# More on $INCLUDE

We all had a long discussion of this in part because users (and we) might have different understandings of what it does. It could be like the C preprocessor, where it is handled before the code is compiled. On the other hand, a user might expect it to behave more like the old Python `execfile` function, where it inserts new template text at runtime. The former has the advantage that the $INCLUDE directives have been handled before any other pre-processor; the use case here is a user who constructs a table from a set of COLUMN objects defined separately. However, that approach won't work for a user who expects to be able to decide at runtime what snippets of a template to incorporate into the label. My implementation is a decent compromise that supports both options. What happens is that a pre-processor identifies every $INCLUDE that refers to a _fixed_ file name and brings that into the file at the time the PdsTemplate object is constructed (and before any user-specified preprocessor). Any $INCLUDE that requires the evaluation of a file name is left alone by the pre-processor and executes during `generate()` or `write()` instead. I think this basically accomplishes what most users would expect, without them even realizing that they expected it.

# TBD

I still plan to update the documentation and to make sure the docstrings are sphinx-friendly. Maybe I can get to that starting sometime next week. Meanwhile, I think this is in a decent state for a merge once we have addressed any other outstanding issues.

**Comment by jnspitale** [comment]
This fixes my sky_summary template.  INCLUDE and GETENV work for me, and the REGEX issues are resolved.  Only thing I notice is a missing UNIT field in the MINIMUM_RIGHT_ASCENSION column in your sky_summary example template.

**Comment by markshowalter** [comment]
For the record, here is a minimal sequence of steps to create create a label from a minimal template, allowing the pre-processor to fill in the missing or incorrect quantities.

```
from pdstemplate import PdsTemplate
from pdstemplate.pds3table import pds3_table_preprocessor

PATH = '/Users/Shared/GitHub/rms-pdstemplate/test_files/'

template = PdsTemplate(PATH + 'sky_summary_template.txt',
                       crlf=True,
                       preprocess=pds3_table_preprocessor,
                       kwargs={'formats':True, 'numbers':True, 'validate':False})

template.write({}, PATH + 'GO_0023_sky_summary.lbl', mode='repair', backup=True)
```
Details. For PDS3, always specify `crlf=True`. The `kwargs` dictionary indicates to add FORMAT and COLUMN_NUMBER values to every COLUMN object. `validate=False` prevents error messages for missing quantities from being reported when the template is written. In `template.write`, `mode='repair'` means that it will only write a new file if the new file would be different from an existing file of the same name. Also, `backup=True` is a good idea because it renames the existing file if a new file is written.

**Comment by jnspitale** [comment]
I'm thinking the elements of pds3_table_preprocessor that aren't specific to tables should be split into a pds3_preprocessor.  This would allow access to thinks like LABEL_VALUE in the inventory template, which needs TABLE_BASENAME, and does not contain a pds3 table.  

At present I am obtaining that information like this:
$ONCE(TABLE_PATH = LABEL_PATH().replace(".lbl",".tab").replace(".LBL",".TAB").split('/')[-1])

**Comment by markshowalter** [comment]
Should be my last updates for this pull request (unless somebody finds something).

- Error messages now include the exact text that triggered the error.
- `RAISE` needed a new implementation.
- `QUOTE_IF` is a handy function to quote a string if the PDS3 standards require it. So FORMAT = A24 but "F10.3", for example.
- `upper_e` input to PdsTemplate forces the "E" in formatted floats to be upper case.
- Clearer distinction between warnings and errors in `pds3_table_preprocessor`. The former can be corrected during runtime; the latter cannot.
- `TemplateAbort` exception forces a label evaluation to terminate.
- `generate()` options `hide_warnings` and `abort_on_error` are used by `pds3_table_preprocessor` to determine how to validate. These are invisible to the user when calling `write()`.
- Turns out there was not a check for duplicated COLUMN names in the validator. There is now.

**Comment by jnspitale** [comment]
Thanks, I was wondering about the use of QUOTE_IF on formats.  Assumed that must be the PDS3 standard, but hadn't had a chance to verify. 

The only comment I have right now is that I am calling Pds3Table._column_values() directly in the index code, so perhaps that should be renamed if you don't object to it being used externally.  The alternative is the index code would have to independently parse the template to get the values needed to generate the table (FORMAT and null constants).  This cannot be done using pdsparser because a raw template is not a valid pds3 label.

**Comment by jnspitale** [comment]
Also, you may want to consider using pathlib.read_text() and write_text().  There are a number of places in the code where you could replace three lines with a single call.

**Comment by jnspitale** [comment]
.. though apparently the newline argument is not available in 3.12, so this is not useful until we're all using 3.13.

**Comment by rfrenchseti** [comment]
And since this is a public package, we should support back to 3.9 until it's end-of-lifed.

**Comment by markshowalter** [comment]
Rob--we agreed not to support 3.9 because match/case is too hard to get rid of.
Joe--Why use _column_values[index][name] when you can use lookup(name, index)?

**Comment by markshowalter** [comment]
If you need to iterate over the columns...
```
for indx in range(1, label.lookup('COLUMNS') + 1):
    # do what you want with label.lookup(name, indx)
```
I would generally prefer that you avoid accessing the internals. If there's a use case I didn't anticipate, let me know.

**Comment by rfrenchseti** [comment]
OK, 3.10 then. But we certainly don't want to require 3.13.

**Comment by markshowalter** [comment]
More for Joe. If you check out the source code for lookup(), you will see numerous ways in which the value returned by the function is not the same as the value found in `_column_values`.  `_column_values` is really just "raw" information pulled out of the label. So you really really should not be accessing `_column_values`.

**Comment by jnspitale** [comment]
I'll take a look at that.  However, for the index generator, the raw values from the template are what I need.

**Comment by markshowalter** [comment]
The errors should go away once `pdslogger` is updated. This has now been tested against `holdings/metadata`, which revealed a distressing number of errors. There's an open task for me to update the documentation with all the new features. However, aside from the documentation shortcomings, this should be ready for pypi.

> I'll take a look at that. However, for the index generator, the raw values from the template are what I need.

It sounds you should be using `old_lookup()` then. This provides the actual values in the current template. It is different from `lookup()`, which returns what the values should be in the new label, after the table has been analyzed. I repeat that you should not be accessing `_column_values()`. If the supported API really doesn't provide something you need, let me know and we'll figure out a good solution.

**Review by rfrenchseti — APPROVED** [review]

**Pull request merged**
